#!/bin/bash -e

todo_folder="${HOME}/.todo"
todo_file="${todo_folder}/`date +%Y-%m-%d`.txt"
todo_flag=' '
done_flag='+'

command_name="$1"
date_params=""
if [ -n "$command_name" ]; then
    shift 1
fi
while getopts ":d:" opt; do
    case $opt in
	d )
	    date_params=$(date -d "$OPTARG" +%Y-%m-%d)
	    if [ -n "$date_params" ]; then
		todo_file=""${todo_folder}/${date_params}.txt""
	    fi
	    ;;
    esac
done
shift $(($OPTIND - 1))
command_params="${@#$0}"

usage () {
    cat <<EOF | xargs -I{} echo -e {}
Usage: $0 [COMMAND] [OPTIONS]
COMMANDS:
\\\\t \\\e[1madd    | a\\\e[0m   \\\e[4mCONTENT\\\e[0m       add CONTENT to todo list.
\\\\t \\\e[1mlist   | ls\\\e[0m  [ \\\e[4mDATE\\\e[0m ]      show DATE\'s todo list, default DATE is today.
\\\\t \\\e[1mremove | rm\\\e[0m  [ \\\e[4mN\\\e[0m ]         remove todo item of line N, default is all lines.
\\\\t \\\e[1mmark   | m\\\e[0m   [ \\\e[4mN\\\e[0m ]         mark todo item of line N as completed, default is all lines.
\\\\t \\\e[1munmark | um\\\e[0m  [ \\\e[4mN\\\e[0m ]         mark todo itemof line N as uncompleted. default is all lines.

OPTIONS:
\\\\t -d  \\\e[4m DATE \\\e[0m  which day to be operated, default is today.
DESCRIPTION:
\\\\t \\\e[4mDATE\\\e[0m               DATE is like '"'today'"' '"'tomorrow'"' '"'last 2 days'"' '"'2017-11-11'"' etc,
\\\\t """"""     """"""""              which can be recognized be GNU date program.
\\\\t \\\e[4mN\\\e[0m                  N is a positive number.
EXAMPLES:
\\\\t todo add 'go shopping'
\\\\t todo add -d 'tomorrow' 'fix bugs'
\\\\t todo ls
\\\\t todo ls -d 'last 2 days'
\\\\t todo rm 2
\\\\t todo m -d 'last day' 2
\\\\t todo um -d 'last day' 1
EOF
}

get_todo_folder () {
    if ! [ -d "$todo_folder" ]; then
	mkdir -p "$todo_folder"
    fi
}

get_todo_file () {
    get_todo_folder
    if ! [ -f "$todo_file" ]; then
	touch "$todo_file"
    fi
}

get_line_number () {
    echo "$command_params" |sed -rn '/^ *[1-9]+ *$/p'
}

ls_item () {
    local target_file="$todo_file"
    if [ -z "$date_params" ]; then
	if [ -n "$command_params" ]; then
	    target_file="$todo_folder/$(date -d "$command_params" +%Y-%m-%d).txt"
	fi
    fi
    if [ -f "$target_file" ]; then
	if [ -z "$(cat $target_file)" ]; then
	    exit 0
	fi
	cat "$target_file" | awk -- " \
{ \
if (\$1 == \"${done_flag}\")
  print \"\\033[92m\", NR, \$0, \"\\033[0m\" ;\
else \
  print \"\\033[91m\", NR, \$0, \"\\033[0m\"; \
} \
" | xargs -I{} echo -e {}
    fi
}

add_item () {
    get_todo_file
    if [ -n "$command_params" ]; then
	echo -e "$todo_flag $command_params \t$(date +%H:%M:%S)" >> "$todo_file"
    else
	usage
    fi
}

op_item () {
    get_todo_file
    local line_number=$(get_line_number)
    if [ -z "$command_params" ]; then
	line_number=""
    else
	if [ -z "$line_number" ]; then
	    usage
	fi
    fi
    local content
    case "$1" in
	mark )
	    content=$(sed -r "${line_number}s/^${todo_flag}/${done_flag}/" $todo_file)
	    ;;
	rm )
	    content=$(sed "${line_number}d" $todo_file)
	    ;;
	unmark )
	    content=$(sed -r "${line_number}s/^\\${done_flag}/${todo_flag}/" $todo_file)
	    ;;
	* )
	    usage
    esac
    if [ -z "$line_number" ]; then
	ls_item
	echo -ne "Are you really want to $1 all todo items ? [Y, N]: "
	local choice_action
	read choice_action
	case "$choice_action" in
	    Y | y | Yes | YES | yes )
		echo -e "$content" > "$todo_file"
		ls_item
		;;
	    N | n | No | NO | * )
		exit 0
		;;
	esac
    else
	echo -e "$content" > "$todo_file"
    fi
}

if [ -z "$command_name" ]; then
    ls_item
    exit 0
fi

case "$command_name" in
    a | add )
	add_item
	;;
    ls | list)
	ls_item
	;;
    rm | remove)
	op_item rm
	;;
    m | mark )
	op_item mark
	;;
    um | unmark )
	op_item unmark
	;;
    * )
	usage
	;;
esac
