#!/bin/bash -e

todo_folder="${HOME}/.todo"
todo_file="${todo_folder}/`date +%Y-%m-%d`.txt"
tmp_file="/tmp/todo_todo"
todo_flag=' '
done_flag='+'

command_name="$1"
if [ -n "$command_name" ]; then
    shift 1
fi
command_params="${@#$0}"

usage () {
    echo -en "  Usage: $0 "
    echo_bold "add "
    echo_underline  "CONTENT"
    echo -n " | "
    echo_bold "ls"
    echo -n " | "
    echo_bold "rm "
    echo_underline "N"
    echo -n " | "
    echo_bold "mark "
    echo_underline "N"
    echo -n " | "
    echo_bold "unmark "
    echo_underline "N"
    echo
    exit 0
}

echo_underline () {
    echo -en "\e[4m${@}\e[0m"
}

echo_bold () {
    echo -en "\e[1m${@}\e[0m"
}

echo_red () {
    echo -en "\e[91m${@}\e[0m"
}

echo_green () {
    echo -en "\e[92m${@}\e[0m"
}

get_todo_folder () {
    if ! [ -d "$todo_folder" ]; then
	mkdir -p "$todo_folder"
    fi
}

get_todo_file () {
    get_todo_folder
    if ! [ -f "$todo_file" ]; then
	touch "$todo_file"
    fi
}

get_line_number () {
    echo "$command_params" |sed -rn '/^ *[1-9]+ *$/p'
}

ls_item () {
    local target_file="$todo_file"

    if [ -n "$command_params" ]; then
	target_file="$todo_folder/$(date -d "$command_params" +%Y-%m-%d).txt"
    fi

    if [ -f "$target_file" ]; then
	if [ -z "$(cat $todo_file)" ]; then
	    exit 0
	fi
	cat "$todo_file" | awk -- " \
{ \
if (\$1 == \"${done_flag}\")
  print \"\\033[92m\", NR, \$0, \"\\033[0m\" ;\
else \
  print \"\\033[91m\", NR, \$0, \"\\033[0m\"; \
} \
" | xargs -I{} echo -e {}
    fi
}

add_item () {
    get_todo_file
    if [ -n "$command_params" ]; then
	echo -e "$todo_flag $command_params \t$(date +%H:%M:%S)" >> "$todo_file"
    else
	usage
    fi
}

op_item () {
    get_todo_file
    local line_number=$(get_line_number)
    if [ -n "$line_number" ]; then
	local content
	case "$1" in 
	    mark )
		content=$(sed -r "${line_number}s/^${todo_flag}/${done_flag}/" $todo_file)
		;;
	    rm )
		content=$(sed "${line_number}d" $todo_file)
		;;
	    unmark )
		content=$(sed -r "${line_number}s/^\\${done_flag}/${todo_flag}/" $todo_file)
		;;
	    * )
		usage
	esac
	echo -e "$content" > "$todo_file"
	ls_item
    else
	usage
    fi
}

if [ -z "$command_name" ]; then
    ls_item
    exit 0
fi

case "$command_name" in
    a | add )
	add_item
	;;
    ls | list)
	ls_item
	;;
    rm | remove)
	op_item rm
	;;
    m | mark )
	op_item mark
	;;
    um | unmark )
	op_item unmark
	;;
    * )
	usage
	;;
esac
